feat/dev-11/create-cart-order
Hydro-Dog/chopp-app pull request #6
Opened 2024-12-27 17:34 UTC by DaniiL10062005

feat/dev-11/create-cart-order

2025-01-02 09:50 UTC, Hydro-Dog commented
Когда заходишь на страницу товара и нажимаешь назад то сбрасывается фильтр. Тут поможет либо хранение текущей категории в searchParams, либо хранение текущей категории в сторе либо использование модалки. Я пока больше за последний вариант. 

Uploading Screen Recording 2025-01-02 at 12.46.37 (1).mov…

2025-01-02 09:51 UTC, Hydro-Dog commented
Все-таки надо постараться сделать чтоб нижний бар не исчезал при переходе в корзину. 
<img width="371" alt="Screenshot 2025-01-02 at 12 51 12" src="https://github.com/user-attachments/assets/c139e0f1-65ec-4871-815d-7cbb847dafd5" />

2025-01-02 10:11 UTC, Hydro-Dog commented
<img width="150" alt="Screenshot 2025-01-02 at 13 10 26" src="https://github.com/user-attachments/assets/769bb880-8a33-4a59-98fc-dafe61e60c3e" />

Надо как-то сохранить на отображении и цену и количество товаров в заказе. Вот так можно попробовать, только я над оформлением не заморачивался.

2025-01-02 10:57 UTC, Hydro-Dog commented
Добавил в бэк эндпоинт [shopping-cart](http://localhost:6001/api/docs#/shopping-cart). Но еще не тестил.

2025-01-08 15:13 UTC, DaniiL10062005 commented on components/main/product-grid-item/product-grid-item.tsx
> +          onPress={() => dispatch(delBasketItems(id))}
Это вынести я не смогу. Мы никак не сможем понять что нажали плюс или минус. При обращении к event в нем нет такого понятия как icon или что-то вроде того

2025-01-24 12:00 UTC, Hydro-Dog commented
<img width="934" alt="Screenshot 2025-01-24 at 15 00 05" src="https://github.com/user-attachments/assets/169a3eb0-4cc5-4c56-b5ff-23e2b0a7b504" />

Ошибки форматирования во многих файлах.

2025-01-24 12:03 UTC, Hydro-Dog commented
<img width="678" alt="Screenshot 2025-01-24 at 15 03 11" src="https://github.com/user-attachments/assets/1c601357-780a-4e33-86fa-abdb383a81de" />

Проверить нейминг всех новых компонентов. Пишем в кебаб кейсе во всех проектах.

2025-01-24 12:18 UTC, Hydro-Dog commented
Давай еще наведем порядок в нейминге. Уславливаемся что сущность корзины называется shoppingCart (через t). Все basket и shoppingCard заменяем на shoppingCart.

2025-01-24 12:40 UTC, Hydro-Dog requested changes

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/product-card.tsx
> +        <Text>qweqwe</Text>
ыыы

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/product-card.tsx
> +export default function ProductCard() {
Этот компонент вообще нигде не используется?

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/shoppingCard.tsx
> +    if (deleteItems.length != basket.items.length) {
Настроить линтер, у меня != подчеркивает 

<img width="621" alt="Screenshot 2025-01-24 at 15 04 38" src="https://github.com/user-attachments/assets/97684bfd-8b52-4d90-9627-c16811e72641" />

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/shoppingCard.tsx
> +  const del = () => {
Нейминг функций это как правило глагол, который что-то описывает. del очень общий термин из которого не понятно назначение функции. ну типа что-то удаляет. Надо назвать конкретнее.

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/shoppingCard.tsx
> +      dispatch(fetchPostShoppingCart({ basket: newBasket }));
fetch - переводится как получить, а post - как отправить. Получается получитьОправитьШоппингКарт. 

Почему бы не назвать переменную сразу basket и записать в виде ({basket})? В пределах этой функции другого баскета у тебя нет, так что не перепутаешь.

2025-01-24 12:40 UTC, Hydro-Dog commented on app/(app)/shoppingCard.tsx
> +        <Text style={styles.header} variant="headlineLarge">
<img width="367" alt="Screenshot 2025-01-24 at 15 14 24" src="https://github.com/user-attachments/assets/1f0fb008-41e7-41de-8dc6-ec437b3f0df5" />

![telegram-cloud-photo-size-2-5233248278596940618-y](https://github.com/user-attachments/assets/ec832e78-5677-48ab-8989-51b2c91eef09)

![telegram-cloud-photo-size-2-5233248278596940621-y](https://github.com/user-attachments/assets/ad131236-561c-4d2f-8b9a-84fa0c3c62b1)


Наверно не будем изобретать велосипед, давай сделаем как на вайлбериз.

2025-01-24 12:40 UTC, Hydro-Dog commented on components/basket/basket-product-card.tsx
> +  const setDeleteThis = () => {
"Установи удаление этого"... Я рассматриваю ее пользу. 
Надо поправить на что-то понятное и читаемое.

2025-01-24 12:40 UTC, Hydro-Dog commented on components/basket/basket-product-card.tsx
> +    const findItem = deleteItems.find((id) => id === item.product.id);
findItem - это глагол, а переменные называем существительными. В локальной области видимости можно и просто item назвать. Понятно что речь идет о каком-то искомом элементе.

2025-01-24 12:40 UTC, Hydro-Dog commented on components/basket/basket-product-card.tsx
> +        const newDeleteItems = prev.filter((id) => id !== item.product.id);
Тоже не существительное.  newDeleteItems -> itemsToDelete/itemsList

2025-01-24 12:40 UTC, Hydro-Dog commented on components/basket/basket-product-card.tsx
> +  deleteItems: number[];
Нейминг аналогично комментам ниже

2025-01-24 12:40 UTC, Hydro-Dog commented on components/basket/basket-product-card.tsx
> +  setDeleteItems: Dispatch<SetStateAction<number[]>>;
Нейминг аналогично комментам ниже

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +  const [inBasket, setInBasket] = useState(false);
Переменная называется "вКорине") 

basketItems. но учитывая что что basket у нас не будет - shoppingCartItems

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +  const [inBasket, setInBasket] = useState(false);
А блин. Я вот даже не понял что это за переменная сначала...

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +  const [inBasket, setInBasket] = useState(false);
Если это логическое значение boolean то называем как правило isЧтотоТам. isBasketEmpty например.

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +        {!inBasket ? (
а basket?.items.length вместо inBasket нельзя использовать?

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +          onPress={() => Decrement(id, basket, dispatch)}
Decrement - как-то вдруг функции начали с большой буквы называться

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +        <Text variant="titleMedium">
Не исправлено.

2025-01-24 12:40 UTC, Hydro-Dog commented on components/main/product-grid-item/product-grid-item.tsx
> +          onPress={() => Increment(id, basket, dispatch)}
Блок с кнопками и счетчиком я бы в отдельный компонент вынес.

2025-01-24 12:40 UTC, Hydro-Dog commented on store/slices/basket-slice/actions.ts
> +>("products/fetchPutProducts", async ({ basket }, thunkAPI) => {
Функция называется fetchPostShoppingCart (выше писал что это неправильно), а тайтл для редакса - "products/fetchPutProducts". Ну это видимо ты с первоисточника не поменял просто. Надо поменять.

2025-01-24 12:40 UTC, Hydro-Dog commented on store/slices/basket-slice/types.ts
> +export type BasketItemPOST = {
postShoppingCartItemDTO

2025-01-24 12:40 UTC, Hydro-Dog commented on store/slices/basket-slice/types.ts
> +  items: BasketItem[];
postShoppingCartDTO

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +import {
<img width="347" alt="Screenshot 2025-01-24 at 15 32 52" src="https://github.com/user-attachments/assets/1da232ae-efa2-42a5-aae5-3fe13fe8293d" />

Посмотри как структура каталогов строится в других метсах. В админке наглядней будет, там свежий код. 

В папке utils -> [index.ts, util1.ts, util2.ts] только файлы. Вложенных папок нет

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +  dispatch: AppDispatch,
dispatch можно внутри функции объявить, просто сделать это не ютилитой а хуком. 

С basket аналогично

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +  dispatch: AppDispatch,
у тебя будет не Decrement а useDecrement, и папка соответсвенно будет hooks а не utils.

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +  id: number,
Опять же не очень понятно. Функция Decrement получает id. С первого взгляда не поймешь как это работает. А вот если б ты назвал аргумент например item, то уже было бы понятно, что функция декремент принимает како-то элемент, который наверно мы удаляем. 

А если тебе целиком item не нужен, то тогда itemId.

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +        return item;
Аналогичные проблемы по неймингу уже описывал выше.

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/decrement/decrement.ts
> +};
В общем. Будет хук useDecrementShoppingCartItem, который внутри себя объявит все нужные dispatch'и и basket'ы. И вернет функцию, которая будет отвечать за декремент. Возвращает. Функцию. См useSuperDispatch.

2025-01-24 12:40 UTC, Hydro-Dog commented on utils/increment/increment.ts
> +export const Increment = (
ну тут аналогично Декременту

2025-01-24 13:44 UTC, DaniiL10062005 commented on components/main/product-grid-item/product-grid-item.tsx
> +        {!inBasket ? (
А зачем искать элемент которого нет в корзине

2025-01-26 14:31 UTC, Hydro-Dog approved these changes

2025-01-26 14:33 UTC, merged